---
- hosts: all
  become: true
  tasks:

    - name: adicionando o arquivo de configuração do apache
      copy:
        src: 'files/httpd.conf'
        dest: '/etc/httpd/conf/httpd.conf'
      notify: 
        - restart apache



    

  handlers:
    - name: restart mysqld
      service:
          name: mysqld
          state: restarted

    - name: restart apache
      service:
          name: httpd
          state: restarted
